### ISSUE TITLE
Hey you interested adding features on this one?

### ISSUE THREAD

**Issue by winstonma** [alvinhkh/buseta#1]
Actually I like this app. I think it load fast. But are you interested on adding some features?

Here is a list in my mind:

1.  Update the KMB ETA API call (the new KMB App is using the new version, it is minor)

2. Add the Sunlight location

3. Change the existing route info page to tab view (1 tab for route info, other tabs for route stop details)

4. (Nice features but more work needed) When you are on the bus, you would like to know the ETA to the destination. Now I do that manually.

Other under the table changes

5. Update the libraries (Now Google is pushing all mobile stuff to Firebase. e.g. Admob)

6. Use [Bottom Sheet](https://developer.android.com/reference/android/support/design/widget/BottomSheetBehavior.html?utm_campaign=android_launch_supportlibrary23.2_022216&utm_source=anddev&utm_medium=blog) to display the detailed stop info

7. Arrival notification (Now the official app is using GPS which is battery draining, use ETA (4) + [GeoFence](https://developer.android.com/training/location/geofencing.html) would be more battery friendly)

I would like to put these features into the app but I don't think it can be done by myself. So I would like to get this feature up together (if you are interested).

**Comment by alvinhkh** [comment]
nice ideas and I am interested.
I think the old method to retrieve route detail will fade out, and the current app will stop working in foreseeable future.
I am actually thinking and just started working on new version from ground up, the current code base isnt good to maintain.

few things in my mind that I didnt work on after ...
- a. structural change that easy to add other providers in future (everything goes to database, so we can use the same ui and database structure when adding new providers)
- b. split route info page into map view (as I want to keep click stop name = get eta update)
- c. mark nearby stop in route stop list view
- d. time and place eta notification, like GoogleKeep
- e. arrive notification
- f. (maybe) use gov database for route

other little things:
- g. update api code, include "ol"
- h. handle multiple "service_type"
- i. use firebase

@winstonma 
reply to your ideas above:
1. ( g )
2. sunlight location? not sure what you mean here
3. ( b ), maybe tabs for "route stops+eta", "timetable", "announcement"
4. keep showing eta notification like current version? I am thinking can we guess the time needed to arrive destination by adding up etas
5. ( i ), definitely
6. maybe map view is good enough to replace the look-like bottom sheet implementation in current version? not sure how you feel on this.
7. ( e ), agree on using GeoFence API

how do you want to work together? as I intend to start fresh. if you didnt leave comment here, i wont share my plan above, as I cant ensure I can finish the first milestone that can publish. any thoughts?

**Comment by winstonma** [comment]
I don't think the old API will be retired as long as the old app is still in the market.

Oh let me make my point clear

The sunlight location: When I sit on the bus, I would not want to sit on the side that have sunlight. Normally I would look at the i) route direction (from destination and start point's geolocation) and ii) day in time (sun would be one the east side during morning time and right side during night time) to determine where is the location of the sun wrt to the bus. It is not shown in the original KMB app but it is useful because people do less prefer sunlight.

ETA to the destination needs more work. For example when you are on the bus. I would like to know what is the estimated time to my destination. And share that with my friend so they know my arrival time (estimated). In order to do this, first of all you need to i) collect ETA for all route, and calculate the time needed between the stops (some data processing). And store those info into some server. I guess Google App Engine is a good place. Then at least you have the data for the Estimated Time required between stops.

Also I have a pain currently and give you a real example. I take 48X bus in Shatin (I hope you are familiar) and I want to go to Tsuen Wan. I know I would arrive my destination earlier if I switch bus (49X, 43X) at Shing Mun tunnel. I would like the App to tell me if it is better off to switch the bus (because there might be time that you need to wait 10 minutes at the interchange, that makes it worthless switching bus).

For Map View or bottom sheet I think anything would do. But before coding I think it is best to work out a prototype (in powerpoint or [InVision](https://www.invisionapp.com). It should spend less than one day. When we feel like "This is the app" then we can start coding.

For collaboration, we can first list out the work and then we can do that one by one, based on priority. Each of us can work on different features. Merging is required.

For modifying the existing code base or start from stretch I think it is too early to decide. I think both are fine since the existing code is not extremely huge.

**Comment by winstonma** [comment]
I created a very simple [Prototype](https://invis.io/96A64QO7G#/215901872_Main_Page). Feel free to comment.

**Comment by alvinhkh** [comment]
I don't think etav2 will be retired soon, but as I remember neither old or new mobile app is using API call to retrieve stop list. currently buseta is using a mix of lwb and old kmb website API, the old kmb website is replaced by search_kmb_hk. This is one of the main reason why I intend to work from stretch.

**Comment by alvinhkh** [comment]
okay, I agree recommend side of seat based on sunlight is a good addition.
but handle interchange route is difficult using kmb API (at least in previous version of website and mobile app API). 
Things like related route etas (in your UI draft) and etas for stops nearby, seems can't be done efficiently solely depends on kmb API. (i.e. need to use own server, or generate a data file like kmb app) 
any thoughts?

**Comment by winstonma** [comment]
Yeah I think you need to have your own database. The easiest way is to use Firebase. Firebase can also handle user authentication (for storing preference) and also Firebase database is very good.

The downside is the free tier handles 100 concurrent users only. I created a a Firebase version of the BusETA app (Everything is on the Firebase side so no local database code is needed. In the database I put 1. Every route info (except news) 2. User preferences). But still I am not sure if it scale.

But still I think the most important thing is to create a prototype and make sure "that's the tool we need" because building a prototype take hours but building the actual app takes days.

**Comment by winstonma** [comment]
By the way do you use Mac? I created the prototype using Keynote.

**Comment by alvinhkh** [comment]
yes, i use mac

**Comment by winstonma** [comment]
Good. I use Keynote & InVision to build the prototype. If you agree in building prototype. I use [Android UI in Keynote](https://drive.google.com/file/d/0B02r04yH2xUXeXZZM1NubDh0dlk/view?usp=sharing) and InVision to build a prototype. This file is a free preview of [Keynotopia](http://keynotopia.com) template.

We can also use Slack to communicate.

**Comment by alvinhkh** [comment]
for slack invitation, your email?

**Comment by winstonma** [comment]
winstonma@ymail.com

**Comment by thomas930** [comment]
Any Updates on it?
I can be a Beta Tester of the App!
