### ISSUE TITLE
Buseta not work again? API changed by KMB?

### ISSUE THREAD

**Issue by mulderbert** [alvinhkh/buseta#15]

**Comment by alvinhkh** [comment]
yes. i have uploaded new updates on 5th, but it takes time to get play store approve.

**Comment by mulderbert** [comment]
Hi Alvin,
Thanks a lot for your great work. 真心感激你呢嗰app.
IT 小薯仔一名 Francis. 

傳送自 Android 上的 Yahoo Mail 
 
  在 2020 年 11月 月 9 日 週一，時間： 8:49 上午，Alvin<notifications@github.com>寫道：   


yes. i have uploaded new updates on 5th, but it takes time to get play store approve.

**Comment by alvinhkh** [comment]
in case play store take forever to approve, 
here is the apk: https://www.dropbox.com/s/iw7q2e7z330o1ey/buseta-1.4.8.apk?dl=1

**Comment by mulderbert** [comment]
Thanks Alvin, it works!


    On Monday, November 9, 2020, 02:24:56 PM GMT+8, Alvin <notifications@github.com> wrote:  
 
 


in case play store take forever to approve,
here is the apk: https://www.dropbox.com/s/iw7q2e7z330o1ey/buseta-1.4.8.apk?dl=1
