### ISSUE TITLE
BusETA need fix

### ISSUE THREAD

**Issue by thomas930** [alvinhkh/buseta#2]
http://www.kmb.hk/tc/news/press/archives/news201706092521.html
KMB announced the old app is retired...

**Comment by winstonma** [comment]
@alvinhkh Maybe KMB replaced the ETA API V2 with V3 that's why the App is not working. Would you mind modifying the code and release a new version? Thanks

I guess it would be the ETA_API_HOST in Constants.java

**Comment by thomas930** [comment]
Ya...
Details have already been sent to @alvinhkh via email.
(Thanks Alvin fix it!)

**Comment by alvinhkh** [comment]
fixed.

**Comment by thomas930** [comment]
App cannot be installed using my S2 (Android 4.1.2) and C9 Pro (Android 6.0.1) with the latest app. (Fixed!)

**Comment by alvinhkh** [comment]
@thomas930 updated try download again

**Comment by thomas930** [comment]
Thanks...
App can be installed and most function is work now. 

Some bug is found: Route number cannot be shown (Maybe due to white font colour?)when doing query. 

Update：
S2 (Android 4.1.2) 
* can display the router number, 
* Wheelchair icon cannot be displayed (Problem can be ignored because of using old android old S2). 

C9 Pro (Android 6.0.1)
*  cannot display the router number. 

(Fixed!)

**Comment by winstonma** [comment]
@thomas930 Actually I experienced the same "route not displaying" problem (Similar to your C9 Pro).

But Thanks @alvinhkh for fixing this
