### ISSUE TITLE
Multiple following list

### ISSUE THREAD

**Issue by ericksli** [alvinhkh/buseta#4]
It would be nice to have multiple following list as user like me may bookmark multiple route+stop for routes in both directions (e.g. list with routes from Home to work and list with routes from work to home). These items get mixed and make me difficult to browse which bus should take when I arrive to the bus stop, especially I also follow route+stop at interchange stop.

This feature could be implemented by:

- replacing the list to ViewPager with list fragment representing different following lists
- add new table to represent following list
- add new foreign key to the favourite table

**Comment by winstonma** [comment]
Yes, I totally agree that bookmarking route (or stop) is better than bookmarking stops. If you need multiple route then it is better to add the location support - the stops will be displayed based on the route and the current location.

But AFAIK location support is not included, I guess location support need to add first.

**Comment by stanleylhs** [comment]
Following this same note,  can we reorder the list? As of now the list is sort by descending time, which my most frequently used routes end up at the bottom of the list, which takes some times to scroll to.

**Comment by alvinhkh** [comment]
resolved. implemented in release 1.3.4
