### ISSUE TITLE
WebView problem after recent updates

### ISSUE THREAD

**Issue by rgrk11** [alvinhkh/buseta#6]
Thank you for your updates.  Unfortunately, my android 8.1 device is unable to properly display bbi and timetable of nwst. You can refer to [[R1]](https://stackoverflow.com/questions/54516798/webview-loaddata-not-working-on-8-1-and-9-0) for the reason why it happens after setting targetSdkVersion to 29. As suggested in [[R2]](https://developer.android.com/reference/android/webkit/WebView.html#loadData(java.lang.String,%20java.lang.String,%20java.lang.String)), all usage of `webView.loadData` in `WebViewFragment` should be replaced by `webView.loadData(Base64.encodeToString(contentHtml?.toByteArray(), Base64.NO_PADDING), "text/html; charset=UTF-8", "base64")`.

Furthermore, the addition of `webView.setBackgroundColor(Color.TRANSPARENT)` is another reason that hinders WebView content partially. More precisely, using it with `webView.loadData` results in black WebView background, which in turn hides some words in black color. I suggest to only use it with  `webView.loadUrl(contentUrl)` which is newly added [here](https://github.com/alvinhkh/buseta/blob/f9226a7a94bdc4862d81da922f0341cc4048ae0a/app/src/main/java/com/alvinhkh/buseta/ui/webview/WebViewFragment.kt#L60).

**Comment by alvinhkh** [comment]
thanks
