### ISSUE TITLE
updated 1.4.4

### ISSUE THREAD

**Issue by Tang6123** [alvinhkh/buseta#9]
您好， 已 updated 1.4.4 仍未能使用 請問為何？

**Comment by alvinhkh** [comment]
係kmb用唔到，定其他？試下去設定>清除暫存路線

**Comment by Tang6123** [comment]
您好 試了城巴 沒有問題是九巴路線不能用 

Sent from Yahoo Mail on Android 
 
  On Wed, 17 Jun 2020 at 10:49, Alvin<notifications@github.com> wrote:   


係kmb用唔到，定其他？試下去設定>清除暫存路線

**Comment by alvinhkh** [comment]
設定>清除暫存路線。試了？
路線資料會載入？淨係冇到站時間？

**Comment by Tang6123** [comment]
您好 已試了清除路線 重新輸入路線是見到路線資料 沒有了到站時間

Sent from Yahoo Mail on Android 
 
  On Wed, 17 Jun 2020 at 10:58, Alvin<notifications@github.com> wrote:   


設定>清除暫存路線。試了？
路線資料會載入？淨係冇到站時間？

**Comment by alvinhkh** [comment]
確定設定>版本是 1.4.4（14400）？
電話上search.kmb.hk能夠見到到站時間嗎？
電話係咩型號？

**Comment by Tang6123** [comment]
九巴 apps
九巴 Apps 是正常的，手機是Sony xperia I

Sent from Yahoo Mail on Android 
 
  On Wed, 17 Jun 2020 at 11:14, Alvin<notifications@github.com> wrote:   


確定設定>版本是 1.4.4（14400）？
電話上search.kmb.hk能夠見到到站時間嗎？
電話係咩型號？

**Comment by Tang6123** [comment]
Sent from Yahoo Mail on Android 
 
  On Wed, 17 Jun 2020 at 11:27, Gut T<guttanghk@yahoo.com.hk> wrote:   

九巴 apps
九巴 Apps 是正常的，手機是Sony xperia I

Sent from Yahoo Mail on Android 
 
  On Wed, 17 Jun 2020 at 11:14, Alvin<notifications@github.com> wrote:   


確定設定>版本是 1.4.4（14400）？
電話上search.kmb.hk能夠見到到站時間嗎？
電話係咩型號？

**Comment by alvinhkh** [comment]
Android version係咩？
上唔上到search.kmb.hk網頁版睇到站時間？

**Comment by Tang6123** [comment]
Android 10 

Sent from Yahoo Mail on Android 
 
  On Wed, 17 Jun 2020 at 19:00, Alvin<notifications@github.com> wrote:   


Android version係咩？
上唔上到search.kmb.hk網頁版睇到站時間？

**Comment by alvinhkh** [comment]
如果已經update咗1.4.4（14400），上到官網而唔係app睇到到站時間，其他mtr/城巴又睇到，清除過暫存路線，load到路線資料，已經係最新Android  的話，諗唔到點解會load唔到。。
可唔可以試埋del咗個app 再重新安裝？但咁會冇矖追蹤咗嘅路線

**Comment by Tang6123** [comment]
已重新裝過幾次，未sent email給你們時已重新裝過2次了，sent 左 email又重新裝2次，所以都係唔明白，一陣剷左個apps reset電話再裝。

Sent from Yahoo Mail on Android 
 
  On Wed, 17 Jun 2020 at 19:43, Alvin<notifications@github.com> wrote:   


如果已經update咗1.4.4（14400），上到官網而唔係app睇到到站時間，其他mtr/城巴又睇到，清除過暫存路線，load到路線資料，已經係最新Android 的話，諗唔到點解會load唔到。。
可唔可以試埋del咗個app 再重新安裝？但咁會冇矖追蹤咗嘅路線

**Comment by kakays** [comment]
cannot search for ETA at search.kmb.hk
the web page said kmb is updating their system at search.kmb.hk
so this app seems not working
